# Generated by Django 5.2.5 on 2025-09-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_pipelinestage_tag_lead_pipeline_stage_lead_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="pipeline_stage",
        ),
        migrations.AddField(
            model_name="lead",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="profile_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name="PipelineStage",
        ),
    ]
