# Generated by Django 5.2.5 on 2025-09-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_remove_lead_pipeline_stage_lead_is_archived_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
