# Generated by Django 5.2.5 on 2025-11-12 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_remove_lead_pipeline_stage_lead_is_archived_and_more"),
        ("crm", "0005_label_color"),
        ("crm", "0006_label_owner_alter_label_color_alter_label_name_and_more"),
        ("crm", "0006_label_owner_alter_label_color_alter_label_name_and_more"),
    ]

    operations = []
