name: backend-ci

on:
  pull_request:    # runs on every PR

jobs:
  test:
    runs-on: self-hosted

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: facrm
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: backend
        run: pip install -e ".[dev]"

      - name: Wait for Postgres
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5433 -U postgres && break
            echo "⏳ Waiting for Postgres..."
            sleep 2
          done

      - name: Run migrations
        working-directory: backend
        env:
          DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5433/facrm
        run: python manage.py migrate

      - name: Run lint
        working-directory: backend
        run: ruff check .

      - name: Run tests
        working-directory: backend
        env:
          DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5433/facrm
        run: pytest -q
