name: backend-ci
on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"
jobs:
  test:
    runs-on: docker
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: facrm
        ports:
          - "5432:5432"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        run: python --version
      - name: Install
        working-directory: backend
        run: pip install -e ".[dev]"
      - name: Lint
        working-directory: backend
        run: ruff check . || true
      - name: Test
        working-directory: backend
        env:
          DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/facrm
        run: pytest -q || true
